version: '3.9'

services:

  producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    environment:
      - send_interval=150

  consumer:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    volumes:
      - ./results:/project/results

  # ----------------------- RocketMQ -----------------------
  namesrv:
    image: apacherocketmq/rocketmq:4.8.0-alpine
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  broker:
    image: apacherocketmq/rocketmq:4.8.0-alpine
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./rocketmq/broker.conf:/home/rocketmq/rocketmq-4.8.0/conf/broker.conf
      - ./rocketmq/broker/logs:/home/rocketmq/logs
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/rocketmq-4.8.0/conf/broker.conf
    depends_on:
      - namesrv