version: '3.9'

services:

  producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    environment:
      - send_interval=75
      - spring_cloud_stream_binders_localrabbit_environment_spring_rabbitmq_host=rabbitmq

  consumer:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    volumes:
      - ./results:/project/results
    environment:
      - spring_cloud_stream_binders_localrabbit_environment_spring_rabbitmq_host=rabbitmq

#    ----------------------- RabbitMQ -----------------------
  rabbitmq:
    image: "rabbitmq:3.8.14-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"