server:
  port: 8081


spring:

  cloud:
    stream:
      bindings:
        receiveTestObject-in-0:
          destination: my-topic
          group: myconsumergroup
          binder: local_rabbit
          contentType: application/json
          consumer:
            concurrency: 50 # (for RocketMQ) WORKS

      rocketmq:
        binder:
          name-server: localhost:9876 # local ->  localhost:9876 | docker -> namesrv:9876 WORKS

      rabbit:
        bindings:
          receiveTestObject-in-0:
            consumer:
              containerType: SIMPLE # WORKS
              maxConcurrency: 50 # WORKS
              acknowledgeMode: AUTO  # WORKS
              txSize: 1000  # WORKS

      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost # local -> localhost | docker -> rabbitmq
                port: 5672 # WORKS
                username: guest # WORKS
                password: guest # WORKS
                virtual-host: / # WORKS


        local_rocket:
          type: rocketmq


