server:
  port: 8081


spring:

  cloud:
    stream:
      bindings:
        receiveTestObject-in-0:
          destination: my-topic
          group: myconsumergroup
          binder: local_rocket
          contentType: application/json
          consumer:
            concurrency: 1 # 1 is enough (for RocketMQ) WORKS

      binders:
        local_rocket:
          type: rocketmq

      rocketmq:
        binder:
          name-server: localhost:9876 # local ->  localhost:9876 | docker -> namesrv:9876 WORKS


