server:
  port: 8081


spring:

  cloud:
    stream:
      bindings:
        receiveTestObject-in-0:
          destination: my-topic
          group: myconsumergroup
          binder: local_rocket
          contentType: application/json
          consumer:
            concurrency: 1 # (for RocketMQ) WORKS

      rocketmq:
        binder:
          name-server: namesrv:9876 # local ->  localhost:9876 | docker -> namesrv:9876 WORKS

      rabbit:
        bindings:
          receiveTestObject-in-0:
            consumer:
              containerType: SIMPLE # WORKS
              maxConcurrency: 1 # 1 provides best values and is default
              acknowledgeMode: AUTO  # WORKS
              txSize: 200  # WORKS  value suggested in https://www.rabbitmq.com/confirms.html

      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq # local -> localhost | docker -> rabbitmq
                port: 5672 # WORKS
                username: guest # WORKS
                password: guest # WORKS
                virtual-host: / # WORKS


        local_rocket:
          type: rocketmq


